messages:
  prefix: "<gray>[<aqua><bold>HomieCraft <light_purple>SMP<gray>] "

  plugin_enable: "<green>HomieCraft Plugin wurde gestartet!"
  plugin_disable: "<red>HomieCraft Plugin wurde gestoppt!"

  join: "<red>Der Spieler <red><italic>%player% <red>hat den Server betreten!"
  first_join: "<aqua>%player% <red>ist zum ersten Mal auf HomieCraft!"
  leave: "<red>Der Spieler <red><italic>%player% <red>hat den Server verlassen!"

  diamonds_found: "<red>Du hast <aqua>%amount% Diamanten <red>gefunden!"
  
  spawn_set: "<green>Spawn wurde gesetzt!"
  spawn_teleport: "<red>Du wurdest zum Spawn teleportiert!"
  no_spawn_set: "<red>Es wurde noch kein Spawn gesetzt!"
