messages:
  prefix: "<gray>[<aqua><bold>HomieCraft <light_purple>SMP<gray>] "

  plugin_enable: "<green>HomieCraft Plugin wurde gestartet!"
  plugin_disable: "<red>HomieCraft Plugin wurde gestoppt!"
  
  help: "<aqua>HomieCraft Commands: <gray>/spawn, /setspawn, /tpa ..."
  reload: "<green>Plugin wurde neu geladen!"
  no_permission: "<red>Du bist nicht dazu berechtigt."
  unknown_command: "<red>Diesen Befehl gibt es nicht! Mache <dark_red>/help</dark_red> für Hilfe."

  join: "<red><italic>%player% </i><gray>hat den Server betreten!"
  first_join: "<aqua><i>%player% </i><purple>ist zum ersten Mal auf HomieCraft!"
  leave: "<red><italic>%player% </i><gray>hat den Server verlassen!"

  diamonds_found: "<red>Du hast <aqua>%amount% Diamanten <red>gefunden!"
  
  spawn_set: "<green>Spawn wurde gesetzt!"
  spawn_teleport: "<gray>Du wurdest zum Spawn teleportiert!"
  no_spawn_set: "<red>Es wurde noch kein Spawn gesetzt!"

  tpa_sent: "<gray>Anfrage an <red>%target%</red> gesendet."
  tpa_accept: "<green>Anfrage angenommen."
  tpa_accepted: "<green>Teleport wird gestartet..."
  tpa_deny: "<red>Anfrage abgelehnt."
  tpa_denied: "<red>Deine Anfrage wurde abgelehnt."
  tpa_expired: "<red>Anfrage abgelaufen."
  tpa_none: "<red>Keine Anfrage vorhanden."
  tpa_cancel_move: "<red>Teleport abgebrochen, du hast dich bewegt."
  tpa_teleport: "<green>Teleportiert!"
  tpa_self: "<red>Du kannst dir selbst keine Anfrage senden."
  tpa_offline: "<red>Spieler ist offline."
  tpahere_sent: "<gray>Anfrage gesendet an <red>%target%</red> (zu dir)"
  tpa_auto_on: "<green>Auto-TPA aktiviert"
  tpa_auto_off: "<red>Auto-TPA deaktiviert"
  tpa_toggle_on: "<green>TPA aktiviert"
  tpa_toggle_off: "<red>TPA deaktiviert"
  tpa_blocked: "<red>Dieser Spieler blockiert TPA-Anfragen."
  tpa_received: "<gray>----------\n<red>%player%</red> möchte sich zu dir teleportieren\n\n<green><click:run_command:'/tpaccept'><hover:show_text:'<gray>Klicke zum Annehmen'>[Annehmen]</hover></click> <red><click:run_command:'/tpdeny'><hover:show_text:'<gray>Klicke zum Ablehnen'>[Ablehnen]</hover></click>\n<gray>----------"
  tpahere_received: "<gray>----------\n<red>%player%</red> möchte dass du zu ihm kommst\n\n<green><click:run_command:'/tpaccept'><hover:show_text:'<gray>Klicke zum Annehmen'>[Annehmen]</hover></click> <red><click:run_command:'/tpdeny'><hover:show_text:'<gray>Klicke zum Ablehnen'>[Ablehnen]</hover></click>\n<gray>----------"

sounds:
  tpa_send: "ENTITY_EXPERIENCE_ORB_PICKUP"
  tpa_receive: "BLOCK_NOTE_BLOCK_PLING"
  tpa_accept: "ENTITY_PLAYER_LEVELUP"
  tpa_deny: "BLOCK_ANVIL_LAND"
  tpa_countdown: "BLOCK_NOTE_BLOCK_HAT"
