name: HomieCraft
version: '1.0-Alpha'
main: de.lucamaximal.homiecraft.core.Main
api-version: '1.21'
author: [ LucaMaximal ]

commands:
  homiecraft:
    description: Hauptcommand
    aliases: [hc]

  spawn:
    description: Teleport zum Spawn

  setspawn:
    description: Setzt den Spawn

  tpa:
    description: Sende eine Teleport-Anfrage

  tpaccept:
    description: Akzeptiere eine Teleport-Anfrage

  tpdeny:
    description: Lehne eine Teleport-Anfrage ab

  tpahere:
    description: Teleportiere Spieler zu dir

  tpaall:
    description: Anfrage an alle Spieler

  tpahereall:
    description: Alle Spieler zu dir teleportieren

  tpaauto:
    description: Auto Accept

  tpatoggle:
    description: Blockiere Anfragen

permissions:
  homiecraft.spawn:
    description: Erlaubt /spawn
    default: true

  homiecraft.setspawn:
    description: Erlaubt /setspawn
    default: op

  homiecraft.reload:
    description: Erlaubt /hc reload
    default: op

  homiecraft.tpa:
    description: Erlaubt /tpa
    default: true

  homiecraft.tpaccept:
    description: Erlaubt /tpaccept
    default: true

  homiecraft.tpdeny:
    description: Erlaubt /tpdeny
    default: true

  homiecraft.tpahere:
    description: Erlaubt /tpahere
    default: true

  homiecraft.tpaall:
    description: Erlaubt /tpaall
    default: op

  homiecraft.tpahereall:
    description: Erlaubt /tpahereall
    default: op

  homiecraft.tpaauto:
    description: Erlaubt /tpaauto
    default: true

  homiecraft.tpatoggle:
    description: Erlaubt /tpatoggle
    default: true
