name: HomieCraft
version: Alpha-1.0
main: de.lucamaximal.homiecraft.Main
api-version: 1.21
author: LucaMaximal
commands:
  homiecraft:
    description: Hauptcommand
    aliases: [hc]

  spawn:
    description: Teleport zum Spawn

  setspawn:
    description: Setzt den Spawn

permissions:
  homiecraft.spawn:
    description: Erlaubt /spawn
    default: true

  homiecraft.setspawn:
    description: Erlaubt /setspawn
    default: op

  homiecraft.reload:
    description: Erlaubt /hc reload
    default: op
