name: HomieCraft
version: Alpha-1.0
main: de.lucamaximal.homiecraft.Main
api-version: 1.21
author: LucaMaximal
commands:
  homiecraft:
    description: Hauptcommand
    aliases: [hc]

  spawn:
    description: Teleport zum Spawn

  setspawn:
    description: Setzt den Spawn
